# Mitce 机场官网：https://mitce.com/aff.php?aff=4905
# Mitce 机场定制配置：https://raw.githubusercontent.com/xtzPioneer/Airport/main/Configs/Clash/Mitce_Full.yaml
# 
# Clash Verg Rev支持：https://github.com/clash-verge-rev/clash-verge-rev
# ClashMetaForAndroid支持：https://github.com/MetaCubeX/ClashMetaForAndroid.git
#
# 规则提供商：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash
# 规则提供商：https://github.com/Loyalsoldier/clash-rules
#
# 图标提供商：https://github.com/Koolson/Qure.git
#
# 支持平台/应用：macOS/Windows/Clash Verg Rev (Version ≥ 1.5.8）
# 支持平台/应用：android/ClashMetaForAndroid (Version >= 2.10.1)
#
# 广告拦截：支持
# 自动测速：支持
# 故障转移：支持
# 负载均衡：支持
# 兜底代理：支持
#
# 微软分流：支持
# 苹果分流：支持
# 谷歌分流：支持
# 国际媒体分流：支持
# 国际互联分流：支持
# 人工智能分流：支持
# 奈飞视频分流：支持
# YouTube 视频分流：支持
# YouTube 音乐分流：支持
# 电报消息分流：支持
# Discord分流：支持
# 国际抖音分流：支持
#
# 区分地区：支持
# 手动切换地区：支持
# 自动切换地区：支持
#
# 更新时间：2024/04/29 19:30

######### 全局配置 #########

ipv6: true
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-name: xd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
secret: "123456"

geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"

geo-auto-update: false
geo-update-interval: 24

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.apple.com"

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  cache-algorithm: arc
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 180.76.76.76
    - 1.1.1.1
    - 8.8.8.8
    - 208.67.222.222
  nameserver:
    - tcp://223.5.5.5
    - tcp://119.29.29.29
    - tcp://180.76.76.76
    - udp://223.5.5.5
    - udp://119.29.29.29
    - udp://180.76.76.76
    - tls://223.5.5.5
    - tls://119.29.29.29
    - tls://180.76.76.76
    - "tcp://[2400:3200::1]"
    - "tcp://[2402:4e00::]"
    - "tcp://[2400:da00::6666]"
    - "udp://[2400:3200::1]"
    - "udp://[2402:4e00::]"
    - "udp://[2400:da00::6666]"
    - "tls://[2400:3200::1]"
    - "tls://[2402:4e00::]"
    - "tls://[2400:da00::6666]"
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - tcp://208.67.222.222
    - udp://1.1.1.1
    - udp://8.8.8.8
    - udp://208.67.222.222
    - tls://1.1.1.1
    - tls://8.8.8.8
    - tls://208.67.222.222
    - "tcp://[2606:4700:4700::1111]"
    - "tcp://[2001:4860:4860::8888]"
    - "tcp://[2620:0:ccc::2]"
    - "udp://[2606:4700:4700::1111]"
    - "udp://[2001:4860:4860::8888]"
    - "udp://[2620:0:ccc::2]"
    - "tls://[2606:4700:4700::1111]"
    - "tls://[2001:4860:4860::8888]"
    - "tls://[2620:0:ccc::2]"
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - tcp://208.67.222.222
    - udp://1.1.1.1
    - udp://8.8.8.8
    - udp://208.67.222.222
    - tls://1.1.1.1
    - tls://8.8.8.8
    - tls://208.67.222.222
    - "tcp://[2606:4700:4700::1111]"
    - "tcp://[2001:4860:4860::8888]"
    - "tcp://[2620:0:ccc::2]"
    - "udp://[2606:4700:4700::1111]"
    - "udp://[2001:4860:4860::8888]"
    - "udp://[2620:0:ccc::2]"
    - "tls://[2606:4700:4700::1111]"
    - "tls://[2001:4860:4860::8888]"
    - "tls://[2620:0:ccc::2]"
    - tcp://223.5.5.5
    - tcp://119.29.29.29
    - tcp://180.76.76.76
    - udp://223.5.5.5
    - udp://119.29.29.29
    - udp://180.76.76.76
    - tls://223.5.5.5
    - tls://119.29.29.29
    - tls://180.76.76.76
    - "tcp://[2400:3200::1]"
    - "tcp://[2402:4e00::]"
    - "tcp://[2400:da00::6666]"
    - "udp://[2400:3200::1]"
    - "udp://[2402:4e00::]"
    - "udp://[2400:da00::6666]"
    - "tls://[2400:3200::1]"
    - "tls://[2402:4e00::]"
    - "tls://[2400:da00::6666]"
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.opendns.com/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "+.lan"
    - "+.local"
  fallback-filter:
    geoip: true
    geoip-code: CN

######### 锚点配置 #########

# 策略组

pr: &pr
  type: select
  proxies:
    - 自动选择
    - 手动选择
    - 自动切换
    - 手动切换
    - 故障转移
    - 负载均衡
    - 香港节点
    - 台湾节点
    - 日本节点
    - 韩国节点
    - 新加坡节点
    - 美国节点

re: &re
  proxies:
    - 香港节点
    - 台湾节点
    - 日本节点
    - 韩国节点
    - 新加坡节点
    - 美国节点

de: &de
  type: select
  proxies:
    - 节点选择
    - 自动选择
    - 手动选择
    - 自动切换
    - 手动切换
    - 故障转移
    - 负载均衡
    - 香港节点
    - 台湾节点
    - 日本节点
    - 韩国节点
    - 新加坡节点
    - 美国节点
    - 直连

cn: &cn
  type: select
  proxies:
    - 直连
    - 节点选择
    - 自动选择
    - 手动选择
    - 自动切换
    - 手动切换
    - 故障转移
    - 负载均衡
    - 香港节点
    - 台湾节点
    - 日本节点
    - 韩国节点
    - 新加坡节点
    - 美国节点

globe: &globe
  type: select
  proxies:
    - 节点选择
    - 自动选择
    - 手动选择
    - 自动切换
    - 手动切换
    - 故障转移
    - 负载均衡
    - 香港节点
    - 台湾节点
    - 日本节点
    - 韩国节点
    - 新加坡节点
    - 美国节点

# 订阅更新和延迟测试

p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: "http://cp.cloudflare.com/generate_204"
    interval: 600
    tolerance: 50

uta: &uta
  url: "http://cp.cloudflare.com/generate_204"
  interval: 300
  tolerance: 50
  include-all-providers: true

# 规则行为

rule-anchor:
  ip: &ip
    type: http
    interval: 86400
    behavior: ipcidr

  domain: &domain
    type: http
    interval: 86400
    behavior: domain

  classical: &classical
    type: http
    interval: 86400
    behavior: classical

######### 远程订阅配置 #########

# 1. url 里填写自己的订阅链接，多个订阅链接时名称不能重复。
# 2. url 中可以填写 Base64 订阅链接字符串。
# 3. 请使用 Clash 类型订阅链接填入引号""内使用。
# 4. 或可使用通用订阅链接通过 Sub-Store 进行订阅转换(用于 Stash)。

proxy-providers:
  Mitce:
    <<: *p
    path: ./proxy-providers/Mitce.yaml
    url: ""

######### 定义代理组配置 #########

proxy-groups:
  # 节点选择
  - name: 节点选择
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Proxy.png"
    <<: *pr

  - name: 手动选择
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Static.png"
    type: select
    include-all-providers: true

  - name: 手动切换
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Static_1.png"
    type: select
    <<: *re

  # 回退/转移
  - name: "故障转移"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Available_1.png"
    type: fallback
    <<: *uta

  # 广告拦截
  - name: "广告拦截"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/AdBlack.png"
    type: select
    proxies: [拒绝, 绕过]

  # 苹果服务
  - name: "苹果服务"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Apple.png"
    <<: *cn

  - name: "苹果系统更新"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Apple_Update.png"
    <<: *cn

  # 微软服务
  - name: "微软服务"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Microsoft.png"
    <<: *cn

  - name: "GitHub"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/GitHub.png"
    <<: *globe

  # 谷歌服务
  - name: "谷歌服务"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Google_Search.png"
    <<: *globe

  - name: "YouTube 视频"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/YouTube.png"
    <<: *globe

  - name: "YouTube 音乐"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/YouTube_Music.png"
    <<: *globe

  # 电报消息
  - name: "电报消息"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Telegram_X.png"
    <<: *globe

  # Discord
  - name: "Discord"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Discord.png"
    <<: *globe

  # 奈飞视频
  - name: "奈飞视频"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Netflix.png"
    <<: *globe

  # AI/人工智能
  - name: "OpenAI"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Bot.png"
    <<: *globe

  # 国际抖音
  - name: "国际抖音"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/TikTok.png"
    <<: *globe

  # 国际媒体
  - name: "国际媒体"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/ForeignMedia.png"
    <<: *globe

  # 国际互联
  - name: "国际互联"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Global.png"
    <<: *globe

  # 地域/区域
  - name: 香港节点
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Hong_Kong.png"
    type: select
    include-all-providers: true
    filter: "港|(?i)HK|(?i)Hong Kong|🇭🇰"

  - name: 台湾节点
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/China.png"
    type: select
    include-all-providers: true
    filter: "台|新北|彰化|(?i)Taiwan|(?i)TW|🇨🇳"

  - name: 日本节点
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Japan.png"
    type: select
    include-all-providers: true
    filter: "日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|(?i)JP|(?i)Japan|🇯🇵"

  - name: 新加坡节点
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Singapore.png"
    type: select
    include-all-providers: true
    filter: "狮城|新加坡|(?i)SG|(?i)Singapore|🇸🇬"

  - name: 韩国节点
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Korea.png"
    type: select
    include-all-providers: true
    filter: "KR|Korea|KOR|首尔|韩|韓|🇰🇷"

  - name: 美国节点
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/United_States.png"
    type: select
    include-all-providers: true
    filter: "美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(?i)US|(?i)United States|🇺🇲"

  # 兜底
  - name: "漏网之鱼"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Final.png"
    <<: *de

  # 自动化
  - name: 自动选择
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Rocket.png"
    type: url-test
    <<: *uta

  - name: 自动切换
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Auto.png"
    type: url-test
    url: "http://cp.cloudflare.com/generate_204"
    interval: 300
    tolerance: 50
    <<: *re

  - name: "负载均衡"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Available.png"
    type: load-balance
    <<: *uta

  # 动作
  - name: "直连"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Direct.png"
    type: select
    proxies: [DIRECT]

  - name: "拒绝"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Reject.png"
    type: select
    proxies: [REJECT]

  - name: "绕过"
    icon: "https://gitee.com/xtzPioneer/Qure/raw/master/IconSet/Color/Bypass.png"
    type: select
    proxies: [PASS]

######### 规则集配置 #########

rule-providers:
  # 苹果服务
  apple-service-classical:
    <<: *classical
    path: ./rule-providers/apple-service-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"

  apple-service-domain:
    <<: *domain
    path: ./rule-providers/apple-service-domain.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.yaml"

  apple-system-ota-classical:
    <<: *classical
    path: ./rule-providers/apple-system-ota-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SystemOTA/SystemOTA.yaml"

  # 微软服务
  microsoft-service-classical:
    <<: *classical
    path: ./rule-providers/microsoft-service-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"

  microsoft-github-classical:
    <<: *classical
    path: ./rule-providers/microsoft-github-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml"

  # 谷歌服务
  google-service-classical:
    <<: *classical
    path: ./rule-providers/google-service-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"

  google-youtube-classical:
    <<: *classical
    path: ./rule-providers/google-youtube-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"

  google-youtube-music-classical:
    <<: *classical
    path: ./rule-providers/google-youtube-music-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.yaml"

  # 电报消息
  telegram-classical:
    <<: *classical
    path: ./rule-providers/telegram-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"

  # Discord
  discord-classical:
    <<: *classical
    path: ./rule-providers/discord-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml"

  # 奈飞视频
  netflix-classical:
    <<: *classical
    path: ./rule-providers/netflix-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_Classical.yaml"

  # AI/人工智能
  open-ai-classical:
    <<: *classical
    path: ./rule-providers/open-ai-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"

  # 国际抖音
  tiktok-classical:
    <<: *classical
    path: ./rule-providers/tiktok-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml"

  # 国际媒体
  globe-media-domain:
    <<: *domain
    path: ./rule-providers/globe-media-domain.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml"

  globe-media-classical:
    <<: *classical
    path: ./rule-providers/globe-media-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml"

  # 国际互联
  globe-classical:
    <<: *classical
    path: ./rule-providers/globe-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml"

  globe-domain:
    <<: *domain
    path: ./rule-providers/globe-domain.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.yaml"

  # 广告拦截
  ad-reject-domain:
    <<: *domain
    path: ./rule-providers/ad-reject-domain.yaml
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"

  # 直连
  direct-domain:
    <<: *domain
    path: ./rule-providers/direct-domain.yaml
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"

  direct-cncidr-ip:
    <<: *ip
    path: ./rule-providers/direct-cncidr-ip.yaml
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"

  direct-lancidr-ip:
    <<: *ip
    path: ./rule-providers/direct-lancidr-ip.yaml
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"

  direct-private-domain:
    <<: *domain
    path: ./rule-providers/direct-private-domain.yaml
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"

  direct-applications-classical:
    <<: *classical
    path: ./rule-providers/direct-applications-classical.yaml
    url: "https://raw.githubusercontent.com/xtzPioneer/Airport/main/Rules/Clash/Direct_Applications_Classical.yaml"

  direct-replenish-domain:
    <<: *domain
    path: ./rule-providers/direct-replenish-domain.yaml
    url: "https://raw.githubusercontent.com/xtzPioneer/Airport/main/Rules/Clash/Direct_Replenish_Domain.yaml"

  # 云计算
  direct-cloud-classical:
    <<: *classical
    path: ./rule-providers/direct-cloud-classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloud/CloudCN/CloudCN.yaml"

######### 分流规则配置 #########

# 注意：规则顺序直接影响规则判定，将会导致分流效果不佳。
# 注意：规则顺序直接影响规则判定，将会导致分流效果不佳。
# 注意：规则顺序直接影响规则判定，将会导致分流效果不佳。

rules:
  # 直连应用
  - RULE-SET,direct-applications-classical,直连

  # 广告拦截
  - RULE-SET,ad-reject-domain,广告拦截

  # 苹果服务
  - RULE-SET,apple-system-ota-classical,苹果系统更新
  - RULE-SET,apple-service-domain,苹果服务
  - RULE-SET,apple-service-classical,苹果服务

  # 微软服务
  - RULE-SET,microsoft-service-classical,微软服务
  - RULE-SET,microsoft-github-classical,GitHub

  # 谷歌服务
  - RULE-SET,google-youtube-classical,YouTube 视频
  - RULE-SET,google-youtube-music-classical,YouTube 音乐
  - RULE-SET,google-service-classical,谷歌服务

  # 电报消息
  - RULE-SET,telegram-classical,电报消息

  # Discord
  - RULE-SET,discord-classical,Discord

  # 奈飞视频
  - RULE-SET,netflix-classical,奈飞视频

  # AI/人工智能
  - RULE-SET,open-ai-classical,OpenAI

  # 国际抖音
  - RULE-SET,tiktok-classical,国际抖音

  # 国际媒体
  - RULE-SET,globe-media-domain,国际媒体
  - RULE-SET,globe-media-classical,国际媒体

  # 国际互联
  - RULE-SET,globe-domain,国际互联
  - RULE-SET,globe-classical,国际互联

  # 直连
  - RULE-SET,direct-private-domain,直连
  - RULE-SET,direct-domain,直连
  - RULE-SET,direct-cncidr-ip,直连
  - RULE-SET,direct-replenish-domain,直连
  - RULE-SET,direct-lancidr-ip,直连
  - RULE-SET,direct-cloud-classical,直连
  - GEOIP,LAN,直连
  - GEOIP,CN,直连

  # 兜底
  - MATCH,漏网之鱼
